Feature/entities
CorpoApp/corpo-event pull request #10
Opened 2020-10-19 21:24 UTC by jeankev

2020-10-21 10:43 UTC, Mal3kit requested changes

2020-10-21 10:43 UTC, Mal3kit commented on src/main/java/com/corpoapp/corpoevent/entity/Corporation.java
> +
We should definitively use Lombok for getter, setter and builder

2020-10-21 10:43 UTC, Mal3kit commented on src/main/java/com/corpoapp/corpoevent/entity/builder/CorporationBuilder.java
> +
If we use Lombok, no need to create Builders.

2020-10-21 10:43 UTC, Mal3kit commented on src/main/resources/init.sql
>  CREATE TABLE registered(
We should verify if we need JPA annotation or not (performance gain ? structure logical ?)

2020-10-21 10:43 UTC, Mal3kit commented on src/test/java/com/corpoapp/corpoevent/entity/builder/EventBuilderTest.java
> +
We should add Container testing for integration tests (maybe in another PR ?)

2020-10-29 12:53 UTC, Mal3kit requested changes

2020-10-29 12:53 UTC, Mal3kit commented on src/main/resources/application.properties
> +quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/corpoapp
change postgres to corpo-app_postgres  (we have to put the service name of the compose here)

2020-10-29 13:37 UTC, Mal3kit approved these changes

2020-10-29 13:37 UTC, tbouyenval approved these changes

2020-10-29 13:44 UTC, Mal3kit approved these changes

2020-10-29 14:02 UTC, merged