add liveness + add dev support to properties
CorpoApp/corpo-event pull request #13
Opened 2020-11-03 23:07 UTC by tbouyenval

2020-11-04 21:59 UTC, thibautstrckr requested changes
Can you divide the PR in 2 PR ?

2020-11-04 21:59 UTC, thibautstrckr commented on src/test/java/com/corpoapp/corpoevent/service/CorporationServiceTest.java
> +@QuarkusTestResource(H2DatabaseTestResource.class)
Why not using postgresql since it's the production database ?

2020-11-12 08:29 UTC, Mal3kit requested changes

2020-11-12 08:29 UTC, Mal3kit commented on src/main/java/com/corpoapp/corpoevent/dto/CorporationDTO.java
> +    public List<User> userList;
List of UserDTO instead of Users

2020-11-12 08:29 UTC, Mal3kit commented on src/main/java/com/corpoapp/corpoevent/dto/UserDTO.java
> +    public List<Corporation> corporationList;
List of CorporationDTO instead of Corporation

2020-11-12 19:55 UTC, Mal3kit approved these changes

2020-11-12 19:56 UTC, merged